---
- name: Setup EC2 with services
  hosts: all
  become: true

  vars:
    mysql_root_password: "StrongMysqlPass123"  # 🔐 Replace with a secure password

  roles:
    - role: mysql
    - role: postgresql
    - role: nginx
    - role: docker_swarm
