---
# roles/mysql/tasks/main.yml

- name: Install MySQL server and Python MySQL dependencies
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: yes
  become: true

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: true

- name: Set MySQL root password using UNIX socket (initial setup)
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    state: present
  become: true

- name: Grant root user access from multiple hosts
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: true
  loop:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
    - "%"
  become: true

- name: Set bind-address to 0.0.0.0 in MySQL config (allow remote access)
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL
  become: true
