- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: true  # Required for apt operations

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: true  # Required for managing services

# Workaround: Set MySQL root password using shell command (only works if no password is set yet)
- name: Set MySQL root password using SQL (only if no password is set)
  shell: |
    mysql -u root <<EOF
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';
    FLUSH PRIVILEGES;
    EOF
  args:
    warn: false
  ignore_errors: true
  become: true  # Required for running mysql command as root

# Now use mysql_user to make sure it's set properly across all hosts
- name: Set MySQL root user with password via Ansible module
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host_all: true
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  become: true  # May not be needed depending on MySQL configuration, but safe to include
