---
- name: Install MySQL server and dependencies
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: yes
  become: true

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: true

- name: Set MySQL root password using shell (only if no password is set)
  shell: |
    mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  ignore_errors: true  # in case password is already set
  become: true

- name: Ensure MySQL root user has password using Ansible module
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host_all: true
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  become: true
