---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Initialize Docker Swarm
  shell: docker swarm init
  register: swarm_init
  failed_when: swarm_init.rc != 0 and 'This node is already part of a swarm' not in swarm_init.stderr
  changed_when: "'Swarm initialized' in swarm_init.stdout"

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Deploy app with Docker Compose
  shell: docker compose -f /home/ubuntu/docker-compose.yml up -d
  args:
    chdir: /home/ubuntu
